name: Emojify PR Title

# delete lines 5-8 and uncomment line 10 to to enable the Emojify PR Title workflow

on:
  pull_request:
    branches-ignore:
      - "**"

# on: pull_request

jobs:
  emojify-pr-title:
    runs-on: ubuntu-latest
    name: Emojify PR Title
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Emojify PR Title
        uses: pineapplelol/emojify-pr-title@v1.2
